# Generated by Django 5.1 on 2024-08-24 09:30

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revolve', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
